### ISSUE TITLE
SSO Application - Disable Fields when Evidence Only = Yes

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#100]
When the "Evidence of an Overflow Only?" = Yes, disable the following fields:

-Start date/time
-End date/time
-Duration
-Estimated Flow
-Estimated Quantity 

Also, be sure that the report can be submitted when these fields are not populated.  The still need to be required when Evidence= No.

**Comment by kanglu666** [comment]
updated. please test

**Comment by JMurk** [comment]
Confirmed complete.
