### ISSUE TITLE
SSO Application - Reports - Occurrence Misspelled 

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#102]
Issue:  The work "Occurrence" is misspelled on both reports multiple times.

![image](https://cloud.githubusercontent.com/assets/5805454/3313854/ae1b9a62-f6e9-11e3-8c45-785c7949ee46.png)

Resolution:  Please update the reports with the correct spelling of Occurrence.

**Comment by tarheelgis** [comment]
Completed please check when changes post

**Comment by JMurk** [comment]
Confirmed complete.
