### ISSUE TITLE
SSO Application - Report - Watershed Not Printing

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#104]
Issue:  The "Name of Watershed" field is not printing any value.

![image](https://cloud.githubusercontent.com/assets/5805454/3314013/e4ba69d4-f6eb-11e3-95a1-ac051ff66739.png)

Resolution:  I suspect there is a discrepancy between the City and KCI databases, but please investigate and resolve accordingly.

**Comment by tarheelgis** [comment]
Updated check when changes post

**Comment by JMurk** [comment]
Confirmed complete.
