### ISSUE TITLE
SSO Application - Missing Overflowig Feature Types

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#106]
Issue:  It appears as if there are some values missing from the Overflowing feature drop down.  Please make sure that all values in the domain are also in the application drop down.

![image](https://cloud.githubusercontent.com/assets/5805454/3344796/79bf6ef2-f8af-11e3-9236-af7b4e73c7b2.png)

**Comment by kanglu666** [comment]
when you create an new SSO, you can only identify these four layers, to get the associate overflowing feature. that's y the drop down just apply these four layers.

**Comment by JMurk** [comment]
Please add Sump Pump to the list.  There is not a layer for sump pumps, but it can still be an overflowing feature type.

**Comment by kanglu666** [comment]
what field should be the overflow id for sump pump type?
create an new field called "OVERFLOW_SP_ID" in db?

**Comment by JMurk** [comment]
There is not a feature class for sump pumps, therefore there is no ID.  The user will only select this type from the Overflowing feature field on the "Features" page.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
