### ISSUE TITLE
SSO Application - Assigned User Confirmation Modal Screen

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#107]
Issue:  There are numerous grammatical errors on the assigned user confirmation message modal screen.

![image](https://cloud.githubusercontent.com/assets/5805454/3359082/af4bcc1e-fae4-11e3-8f4c-fdc8ea8918e2.png)

Resolution:  Please update the message to read  "The SSO has been successfully assigned to the selected user."

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Please add this pop-up when assigning to a user of an existing SSO

**Comment by kanglu666** [comment]
updated for existing sso from inbox page.
one thing to make sure, the send email to individual assigned to user, will only happen when the SSO status is in progress. that's the original design.

**Comment by JMurk** [comment]
Still not working from the inbox.  Please revisit.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
