### ISSUE TITLE
SSO Application - Clear Graphics - Does Not Clear Locate Pushpin

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#108]
Please extend the clear graphics functionality to clear the blue push pin that is created as a result of an address location.

![image](https://cloud.githubusercontent.com/assets/5805454/3473126/35f42a08-02d4-11e4-824a-6b37221852fb.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
