### ISSUE TITLE
SSO Application - Observed By - Use Full Name

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#109]
Issue: Observed By is auto-populating with the username of the logged in user.

![image](https://cloud.githubusercontent.com/assets/5805454/3474067/35544abe-02df-11e4-9fd0-5cb61f899af9.png)

Resolution:  Please auto-populate with the FULLNAME of the logged in user.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
