### ISSUE TITLE
field dependency does not work

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#11]
Issue:
When the user toggles on the "Other" field in the Reasons for Overflow section, the system does not require that the Description field be populated.  

Steps to reproduce:
1. Create a new SSO form, including all required fields
2. Toggle on the Other field.  Do not populate Description.
3. Tap Save.

Fix:
If Other is one of the Reasons for Overflow (even if there are multiple fields, including Other, toggled on), the system should display the notification message if Other - Description is not populated (just like for other required fields).

**Comment by kanglu666** [comment]
done
