### ISSUE TITLE
SSO Application - Black Text/Brown Background

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#112]
Please fix **ALL** modal screen messages to have white text on top of the brown backgrounds.

![image](https://cloud.githubusercontent.com/assets/5805454/3496162/419a5ff4-05df-11e4-9185-eeaa525d3b2c.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
