### ISSUE TITLE
SSO Application - Assigned To Conformation Message Typo

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#113]
Issue:  When Assinged To is null, the pop-up message stating the field is required has a minor typo.

![image](https://cloud.githubusercontent.com/assets/5805454/3496925/11c9043a-05e7-11e4-8b32-2697a079f085.png)

Resolution:  Please change "TO" to "To"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Complete.
