### ISSUE TITLE
SSO Application - Assigned To Dropdown is Blank

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#114]
Issue:  There are no values in the Assigned To dropdown list. I'm guessing this stems from changing the application to point to the cityUsers DB.

![image](https://cloud.githubusercontent.com/assets/5805454/3497030/e787e05a-05e7-11e4-9034-86d693b171b6.png)

Resolution:  Please re-point the Assigned To field to the proper table/column.

**Comment by kanglu666** [comment]
updated, now this field is hitting cityusers data.

**Comment by JMurk** [comment]
Confirmed complete.
