### ISSUE TITLE
SSO Application - Discrepancy Scale Warning - Message Format

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#115]
Issue:  The scale warning message for SSOs and Discrepancies differ in format.

![image](https://cloud.githubusercontent.com/assets/5805454/3497816/1c081b04-05ef-11e4-8dcb-31a98ca49e58.png)

![image](https://cloud.githubusercontent.com/assets/5805454/3497822/26dd90ea-05ef-11e4-93a9-3d4701a7349f.png)

Resolution:  Remove the discrepancy message shown above and repoint the scale warning to the SSO message.  In other words, the message should be exactly the same for SSOs and Discrepancies.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
