### ISSUE TITLE
SSO Application - Discrepancies - Add Photos

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#117]
Please add a photo attachment function within the discrepancy details page.  We will build out here, test, then move to other mobile applications.

**Comment by kanglu666** [comment]
adding photos function has been added in SSO app. please test

**Comment by JMurk** [comment]
No longer populating DATE_LOGGED on the backend.  Please fix.

**Comment by kanglu666** [comment]
fixed

**Comment by JMurk** [comment]
Confirmed complete.
