### ISSUE TITLE
Contact information for DOE needs to be updated

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/SSO-Application-Issues#119]
Issue: contact information for the Dept of the Env has a name spelled incorrectly:
Mr. Dave Lyans should Mr. Dave Lyons

Add a space after the phone number and before the left parentheses.
currently:  410-537-3510(After
change to: 410-537-3510 (After

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
