### ISSUE TITLE
Required field is not required

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#12]
Issue:

The requirements indicate that at least one Possible Cause must be given by the user before the system will allow a save.  This is currently not the case.

Steps to reproduce:
1. Create a new SSO and populate all required fields.  Leave possible causes section blank.
2. Click Save.  The record saves and does not display a notification message.

Fix:
Require that at least one possible cause is toggled on before saving the SSO record

**Comment by kanglu666** [comment]
done
