### ISSUE TITLE
SSO Application: Associated Features: Clean out location remains if change from Clean Out

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/SSO-Application-Issues#122]
Steps to recreate:
1) enter new SSO
2) click on Features
3) select feature type = Clean out
4) select Clean out location = Rear
5) change feature type = Broken pipe

Expected Result:
Clean out location should be blank - but still has the 'Rear'
Clean out location should be uneditable - correct

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
