### ISSUE TITLE
SSO Application: Change order of required fields

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/SSO-Application-Issues#123]
Issue: when creating a new SSO and not entering all required fields and attempt to save, get prompted to enter required field.

Expected response: prompt for each required field in the order they are displayed on the screen.
Actual response: prompts in reverse order for the required fields.

Could the system also place the cursor in the missing field location?

Also, on each prompt for missing field, once the user hits the "OK" button and attempt to navigate to the field, the message appears again.

Make sure all required fields have \* on the display screen.

**Comment by kanglu666** [comment]
put this as future enhancement: reorder prompt for required field.

Could the system also place the cursor in the missing field location?  
Currently, we have no way to do thisfunction.

**Comment by JMurk** [comment]
Closing.
