### ISSUE TITLE
SSO Application: SSO Details should not email without missing clean out location

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/SSO-Application-Issues#124]
Issue: system should not email a report if overflowing feature type -  "clean out" and the clean out location is not selected

Steps to recreate:
1) enter new sso
2) click the features button
3) select feature type = "clean out"
4) don't select clean out location
5) hit back arrow
6) save
7) email

Expected response: display a message: "Must enter clean out location before emailing report"
Actual response: email sent

NOTE:  This field is only required if clean out is selected as the overflowing feature type.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
This is still an issue when a clean out is selected from the map as an overflowing feature.  If the user never returns to the "Features" page, the system will never require them to populate the field.

**Comment by kanglu666** [comment]
done, please test

**Comment by JMurk** [comment]
Confirmed complete.
