### ISSUE TITLE
SSO Application: Discrepancy not getting saved

### ISSUE THREAD

**Issue by rssidlowski** [JMurk/SSO-Application-Issues#125]
Issue: added new discrepancy and attempt to view but not found

Steps to recreate: 
1) click on add discrepancy button at top
2) add discrepancy details and submit
3) go back to map
3) discrepancies at bottom of map is still grayed out

expect to see: discrepancies button clickable.

**Comment by kanglu666** [comment]
1: turn on the discrepancy layer from Setting tab.
2: add discrepany, then the new added one will show on map.
3:discrepancies at bottom of map will be grayed out after new added.

Currently, we have no workflow/design to view the details of the new added discrepancy.

**Comment by JMurk** [comment]
Non issue - closing.
