### ISSUE TITLE
SSO Application - Reports - Header Changes

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#126]
Per stakeholder feedback, change the header to read:

CITY OF BALTIMORE
DEPARTMENT OF PUBLIC WORKS
200 Holliday St
Baltimore, Maryland 21202

Also, in the last line of the report "Separate Sewer System" should have all lowercase s

**Comment by tarheelgis** [comment]
Completed please test when changes post

**Comment by JMurk** [comment]
Confirmed complete.
