### ISSUE TITLE
SSO Application - Reports - Time of Discharge Labels

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#127]
Please update the "TIME OF DISCHARGE" labels to INCLUDE "/TIME" at the end.

So it should be START DATE/TIME: and END DATE/TIME:

![image](https://cloud.githubusercontent.com/assets/5805454/3615956/be6c2468-0dcd-11e4-876d-73a1fb437e80.png)

**Comment by tarheelgis** [comment]
Completed, please test when changes post

**Comment by JMurk** [comment]
Confirmed complete.
