### ISSUE TITLE
SSO Application - Delete Permissions

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#128]
Issue:  Users with a permission of "Editor" are able to delete SSOs that have been submitted.  They should only be allowed to delete an SSO when it is assigned to them AND is In Progress.

Once an SSO is submitted, it should not be able to be deleted by ANYONE.  Only In Progress SSOs should be deleted.

Once the 5-day report has been submitted, it should not be editable by anyone.

Resolution:  Remove the Delete SSO Record button and the ability to edit from the SSO details page when opening from the "Load recently reviewed SSOs" list.

**Comment by kanglu666** [comment]
as we discussed before, 5-day report also can be edit, and the report will pick up the latest one.

right now, admin and reviewer have permission to delete submitted SSOs.
and if the assigned to user = the current log in user, then he has permission to delete the selected submitted SSO.

**Comment by JMurk** [comment]
Once an SSO is submitted, it should not be able to be deleted by ANYONE. Only In Progress SSOs should be deleted.

Please change the permissions accordingly.

**Comment by kanglu666** [comment]
updated, all 5day sso will not be editable.

**Comment by JMurk** [comment]
I was still able to edit a 5 day report.

**Comment by JMurk** [comment]
Scratch that... this was delete permissions, not edit permissions. Closing.

**Comment by JMurk** [comment]
Just re-read the original issue entry.  SSOs that have 5-Day reports been submitted should not be editable by anyone in the application.  Please adjust.

**Comment by kanglu666** [comment]
Joe will verify with city people about this.

**Comment by JMurk** [comment]
Reviewers will not be able to edit or submit after the 5-day report has been submitted.

Admin will be able to edit and submit ONE more 5-day report.  There can not be more than two 5-day reports submitted.

Please adjust permissions accordingly.

**Comment by kanglu666** [comment]
we need to talk about this.
is the second 5-day report the same as the first one? or the second one should be another separate report.
i think the store procedure for the report also need to be updated.

**Comment by JMurk** [comment]
The only difference with the second 5-day report is that is will have "Amended" under the FINAL REPORT label.  

![image](https://cloud.githubusercontent.com/assets/5805454/4264084/fe3c4202-3c13-11e4-8dce-4fd05facbc62.png)

**Comment by kanglu666** [comment]
updated on city dev

**Comment by JMurk** [comment]
There is a small typo on the report.  Change 'IA' to 'IS'

![image](https://cloud.githubusercontent.com/assets/5805454/4508219/a7ad910c-4b13-11e4-994a-49cec0287d31.png)

Everything else looks good and should be ready for push to prod once the schema is updated.

**Comment by JMurk** [comment]
Schema now updated at prod.

**Comment by kanglu666** [comment]
Updated at prod, ready for testing

**Comment by JMurk** [comment]
The 5-day report links in the inbox (and anywhere else they exist) should point to the amended link.  Currently they are pointing to the first 5-day report submitted.

**Comment by kanglu666** [comment]
Now there are three report 24 hour- 5 day- 5 day amend.
Do you want add another 5- day amend link OR just change 5 -day to 5 day amend

**Comment by JMurk** [comment]
Neither.  The 5-Day Report link should always link to the most recent 5-Day report. If there is an amendment, the link will pull that.  If there is no amendment, the link will pull the standard 5-Day report.

**Comment by kanglu666** [comment]
5 day amended report link has been added in the index page and the identify result page
please test in dev

**Comment by JMurk** [comment]
Lu, we do not want a third hyperlink.  Instead there should only be two, with the 5-Day Report hyperlink always pulling the most recent 5-Day report.

There should be a rule/query set when the user clicks the link, the system will check to see if there is an amended report.  If so, it will return that.  If not, it will return the 5-Day.

**Comment by kanglu666** [comment]
updated please Test.

**Comment by JMurk** [comment]
Can you label the Third button, "Load amended SSOs" please?
![image](https://cloud.githubusercontent.com/assets/5805454/4682173/2a5c896c-561a-11e4-93e9-57a670e37181.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
