### ISSUE TITLE
SSO Application - Recently Reviewed not Loading

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#129]
Issue:  When tapping the "Load recently reviewed SSOs" button in the inbox, no results are returned.

Please investigation and resolve accordingly.

**Comment by kanglu666** [comment]
Load recently reviewed SSOs: 
right now it will only load the 5 days report with SSO date later than 01/01/2014.

**Comment by JMurk** [comment]
Closing
