### ISSUE TITLE
Required field notification message text refers to incorrect field

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#13]
Issue:
When Overflow Active = yes (toggled on), several other fields become required.  If the user taps the Save button without populating any additional fields, the system displays a notification indicating the Estimated Volume field is required.  The system displays the same message when that field is then populated.  I believe that the same text is being displayed, but is being triggered by another field being null (possibly Est. Quantity)

Steps to reproduce:
1. Within the SSO data form, toggle Overflow Active = yes.
2. Tap Save.  Populate each field as the system indicates it is required.

Fix:
Please confirm the messages being displayed are referencing the correct trigger.

**Comment by kanglu666** [comment]
it's working fine at my side, we can go through this together if you still have this issue.

**Comment by leeensminger** [comment]
working correctly
