### ISSUE TITLE
SSO Application - Report - Add Overflow Type (5-Day ONLY)

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#130]
Please add Overflow Type (Wet/Dry/Unknown) to the 5-day report.  Maybe under EST. OVERFLOW (GPM) would be best.

![image](https://cloud.githubusercontent.com/assets/5805454/4045629/9ad9f598-2d2b-11e4-8eb5-feceecf151dd.png)

**Comment by tarheelgis** [comment]
Added, please check when changes post

**Comment by JMurk** [comment]
Confirmed complete.
