### ISSUE TITLE
SSO Application - Add Field - CSR Creation Time

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#131]
1. Add a field to the SSO Feature Class of CSR Creation Time (Joe).  
2. Add field ( 311 CSR Creation Time) to SSO Application under SSO Details.  It should be placed at the bottom, above Service Request Type (Lu).

![image](https://cloud.githubusercontent.com/assets/5805454/4081395/53f7a360-2ee7-11e4-82fc-1052447a30ce.png)
1. Once the field is added to the database, it should be added to BOTH reports under SR#.

![image](https://cloud.githubusercontent.com/assets/5805454/4045665/e0c2c760-2d2b-11e4-8f64-92a01632721a.png)

**Comment by JMurk** [comment]
The field has been added in both the dev and production database.  Lu, please add to the application then assign to Eric.

**Comment by kanglu666** [comment]
done on the UI side.

**Comment by JMurk** [comment]
Confirmed complete.
