### ISSUE TITLE
SSO Application - Assigned To Not Populating Correctly

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#132]
Issue:  When creating a new SSO, the Assigned To field is populating with "Neil Kang".  It should be the logged in user.

Resolution:  Please Investigate and resolve accordingly.  Maybe this was never repointed to the cityUsers database?

**Comment by kanglu666** [comment]
fixed, i forgot to remove the hard coded value for my local testing.
should be working correctly now for both prod and dev, please test

**Comment by JMurk** [comment]
Confirmed complete.
