### ISSUE TITLE
SSO Application - After Save, Stuck on Loading

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#133]
Issue:  When trying to save a New SSO, the application sticks on the Loading... screan.  This likely has to do with the schema changes/updates.

![image](https://cloud.githubusercontent.com/assets/5805454/4175721/e43286dc-35e2-11e4-8c9a-f9f1dca71ca8.png)

Resolution:  Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
fixed, please test.

**Comment by JMurk** [comment]
Confirmed complete.
