### ISSUE TITLE
SSO Application - Add Unknown Cause Toggle

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#134]
Please add a toggle in the application for CAUSE_UNKNOWN.  The field should be labeled "Unknown" and controlled with a toggle (default to no)

Place it after Infiltration/Inflow and before Other.

![image](https://cloud.githubusercontent.com/assets/5805454/4180074/7bcd9466-36e5-11e4-9a4d-540d507c9805.png)

**Comment by kanglu666** [comment]
CAUSE_UNKNOWN field has been added in to app for both prod and dev, please test

**Comment by JMurk** [comment]
Please update the current Cause check to include this as a valid option.  When trying to email an SSO with only this caused toggled, the system throws a message explaining that the user needs to select at least 1.  Also, if unknown is toggled, no others should be toggled.  Please add that check.

![image](https://cloud.githubusercontent.com/assets/5805454/4223930/ae8b58a6-3920-11e4-9e53-7f542534a1a8.png)

Also, this message should read: "At least one cause must be selected!"

**Comment by kanglu666** [comment]
CAUSE_UNKNOWN has been added to the cause check function.

**Comment by JMurk** [comment]
Did you update for the 5-day report submittal check as well?  I'm still getting the error there?

**Comment by kanglu666** [comment]
fixed, got an extra white space at the end of  the word "CAUSE_UNKNOWN"...
please test at dev

**Comment by JMurk** [comment]
Confirmed complete on dev, ready for push to prod.

**Comment by JMurk** [comment]
Confirmed complete.
