### ISSUE TITLE
SSO Application - Inbox Set to Neil Kang

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#135]
Issue:  The inbox is permanently displaying "Neil Kang" as the user.  It is not adjusting to the logged in user.

Resolution:  Please investigate and resolve accordingly.

**This issue persists in both Dev and Production**

**Comment by kanglu666** [comment]
fixed, clear cache and test

**Comment by JMurk** [comment]
Confirmed complete in both locations.
