### ISSUE TITLE
SSO Application - Overflow Type Values

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#136]
Please update the Valid Values in the Overflow Type dropdown to:

-Dry Weather
-Wet Weather
-Unknown

![image](https://cloud.githubusercontent.com/assets/5805454/4223759/d250aa22-391e-11e4-9af4-137b966c8db8.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
