### ISSUE TITLE
SSO Application - 311 CSR Creation Time Not Saving

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#137]
**Issue**:  The 311 CSR Creation Time is not saving in **production** (It is working is dev). This is causing the  application to get stuck on the loading screen.

![image](https://cloud.githubusercontent.com/assets/5805454/4223861/d3a2c68e-391f-11e4-868e-47f8834d83d8.png)

**Resolution**: Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
fixed, please clear cache and test.

**Comment by JMurk** [comment]
Confirmed complete.
