### ISSUE TITLE
SSO Application - Photos Not Loading 

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#138]
**Issue**:  Uploaded photos are not being displayed as thumbnails.  Not sure if they are even being uploaded.

![image](https://cloud.githubusercontent.com/assets/5805454/4223908/54e889a4-3920-11e4-96a6-e48fa8d20158.png)

**Resolution**: Please investigate and resolve accordingly

**Comment by kanglu666** [comment]
because the SSO you created missing SSOID without right trigger in place.
image will not load correctly. should be fine now

**Comment by JMurk** [comment]
Confirmed complete.
