### ISSUE TITLE
SSO Application - SSO ID Trigger Not Working

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#139]
**Issue**:  The SSO ID is not populating and causing the application to get stuck on the loading screen.

![image](https://cloud.githubusercontent.com/assets/5805454/4224133/80c06aae-3922-11e4-8029-c9ba0365bb17.png)

**Resolution**: Please investigate the SSOID trigger.

**Comment by kanglu666** [comment]
fixed, please let me know each time when you re-do the sso versionning, that will need rebuild the trigger

**Comment by JMurk** [comment]
Confirmed complete.  Closing.
