### ISSUE TITLE
Overflow Start/End date pickers affect Duration value

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#14]
Issue:
When the user selects a start date or an end date, the system populates the Duration field with another value.  If a value is already in the Duration field, the system overrides it and replaces it with an invalid number.  The number seems to be correlated with the date chosen - depending on the date selections, I was able to generate Duration numbers from 5,000 - 129,000 minutes.

Steps to reproduce:
1. Within the new SSO data form, select a start / end date.
2. Verify the Duration value is updated.

Fix:
Please re-examine the data pickers to identify this and other bugs (see bug #6)

**Comment by kanglu666** [comment]
please test, only you get the same error or unstable, just let me know
