### ISSUE TITLE
SSO Application - Add Initiated Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#140]
Add a fields for Initiated_By and Initiated_Date.  These should be automatically populated with the username of the logged in user and the system date/time.

Joe will add the fields to the schema and Lu will add the populates to the trigger.

**Comment by JMurk** [comment]
These fields have been added to the prod database.  Dev database is down.  

Lu- please update trigger so that these 2 fields are populated upon insert.

**Comment by kanglu666** [comment]
done for prod. both trigger and web services have been updated

**Comment by JMurk** [comment]
These fields are not auto populating.

**Comment by kanglu666** [comment]
updated at dev. 
Initiated_By and Initiated_Date will be auto populated when an new sso created

**Comment by JMurk** [comment]
Confirmed on dev, ready for push to prod.

**Comment by kanglu666** [comment]
updated at prod, please test

**Comment by JMurk** [comment]
Confirmed complete.
