### ISSUE TITLE
SSO Application - Date/Time Submitted  

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#141]
Please add a field to the SSO History Log table that stores the date & time of when the report was submitted.  This should auto populate with the system time when the user taps E-mail.

Lu-  I know we discussed just using EDIT_DATE, but I think that we need something more explicit.  Please try to implement the above in dev.

**Comment by kanglu666** [comment]
SSO History Log table must have the same schema as the SSO feature class,
since EDIT_DATE in the SSO History Log table will always populated the report submitted date. we can just use it,add another field is a waste.

**Comment by JMurk** [comment]
Ok, for now.  May revisit in the future.
