### ISSUE TITLE
SSO Application - Trigger Populate LAST_USER and EDIT_DATE

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#142]
Please add LAST_USER and EDIT_DATE to the trigger.  Both fields should auto populate/update upon every update to the SSO record.

Please implement on dev first.

**Comment by kanglu666** [comment]
done at dev, handle this at client side. please test

**Comment by JMurk** [comment]
Confirmed complete on dev, ready for push to prod

**Comment by kanglu666** [comment]
updated at prod

**Comment by JMurk** [comment]
Confirmed complete.
