### ISSUE TITLE
SSO Application - Preparer Title

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#143]
Please use the cityUsers.dbo.User.Title field to populate the PREPARER_TITLE field.  The Title field has been added to the development database only.

**Comment by kanglu666** [comment]
done at dev, please test.
ps: store procedure for report also updated

**Comment by JMurk** [comment]
This is still using the users role.  Please update.

**Comment by kanglu666** [comment]
by default, if the user has no title in the user table. system will use  "user"  as title.

**Comment by JMurk** [comment]
Confirmed complete for dev, ready fro push to prod.

**Comment by kanglu666** [comment]
done at prod, please test.
ps: store procedure for report also updated

**Comment by JMurk** [comment]
Confirmed complete.
