### ISSUE TITLE
SSO Application - Sort Assigned To Dropdown

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#144]
**Issue**:  The list of values in the Assign To drop down box is not sorted.

![image](https://cloud.githubusercontent.com/assets/5805454/4234964/d8faf07e-39bb-11e4-8dda-a78d97de4c15.png)

**Resolution**:  Please sort alphabetically ascending (A-Z).

**Comment by kanglu666** [comment]
done at dev, please test

**Comment by JMurk** [comment]
Confirmed complete in dev, ready for push to prod

**Comment by kanglu666** [comment]
updated at prod

**Comment by JMurk** [comment]
Confirmed complete.
