### ISSUE TITLE
SSO Application - Editor Cannot Send 24-Hour Report

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#145]
**Issue**:  Users in the Editor role cannot submit a report.

**Resolution**:  Please update so that Editors may submit the 24-hour report only.

**Comment by kanglu666** [comment]
done for dev, please test

**Comment by JMurk** [comment]
Confirmed complete in dev, ready for push to prod.

**Comment by kanglu666** [comment]
updated at prod

**Comment by JMurk** [comment]
Confirmed complete.
