### ISSUE TITLE
SSO Application - Change Modal Screen Message Type

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#146]
Please change the 24-hour success and 5-Day success messages to the browser-style messages.  The modal screens have a tendency to get "stuck" on the screen.

![image](https://cloud.githubusercontent.com/assets/5805454/4235448/6c9e6966-39bf-11e4-82df-a55c674971f5.png)

**Comment by kanglu666** [comment]
done for dev, please test

**Comment by JMurk** [comment]
Confirmed complete in dev, ready for push to prod.

**Comment by kanglu666** [comment]
updated at prod.

**Comment by JMurk** [comment]
Confirmed complete.
