### ISSUE TITLE
SSO Application - Preparer Name

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#147]
Please change the auto populate of PREPARER to be the Full Name instead of the User Name.  Update on Dev first.

Also be sure that REVIEWED_BY is storing Full Name.

**Comment by kanglu666** [comment]
updated at dev

**Comment by JMurk** [comment]
Confirmed complete on dev, ready for push to prod.

**Comment by kanglu666** [comment]
updated at prod, please test

**Comment by JMurk** [comment]
Confirmed complete.
