### ISSUE TITLE
SSO Application - SSO Details - Add Fields to Application & Report

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#148]
Please add the following fields to the application.  They should both be required for report submission:

-Weather Conditions (see WW_VVT_Weather domain for valid codes and description)
-Temperature (integer)

Place the fields under Overflow Type
![image](https://cloud.githubusercontent.com/assets/5805454/4264001/a0da56fc-3c0f-11e4-9f26-a76c091187e4.png)

Within the reports, add under the Occurrence Date and Occurrence Location.
![image](https://cloud.githubusercontent.com/assets/5805454/4264011/f9350388-3c0f-11e4-92d9-bab5e8c8f25f.png)

**Comment by kanglu666** [comment]
done at dev

**Comment by JMurk** [comment]
Confirmed on app, but not in report yet.  Please update.

**Comment by kanglu666** [comment]
where you want to put the new fields in the report?

**Comment by JMurk** [comment]
Under Occurrence Date and Occurrence Location, as it says above.

**Comment by kanglu666** [comment]
reports have been updated, please test

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by JMurk** [comment]
Weather conditions is not printing.
![image](https://cloud.githubusercontent.com/assets/5805454/4292026/882c0892-3dc9-11e4-91d1-3a899fcf2187.png)

**Comment by kanglu666** [comment]
fixed

**Comment by JMurk** [comment]
Confirmed complete.
