### ISSUE TITLE
SSO Application - CAUSE Field Updates

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#149]
The following changes should be made to the application:

-Change the label of "Trash" to "Trash/Debris".
![image](https://cloud.githubusercontent.com/assets/5805454/4264081/cf83df2e-3c13-11e4-8759-0dd4e4ee0ef7.png)

-Sand, Gravel, Rocks field should write to CAUSE_SGR field.

**Comment by kanglu666** [comment]
done at dev.

**Comment by JMurk** [comment]
Confirmed on dev, ready for push to prod.

**Comment by kanglu666** [comment]
prod updated

**Comment by JMurk** [comment]
Please update the report.  

![image](https://cloud.githubusercontent.com/assets/5805454/4286588/1249693a-3d97-11e4-9fea-55b321de033d.png)

**Comment by kanglu666** [comment]
reports have been updated, please test

**Comment by JMurk** [comment]
Confirmed complete.
