### ISSUE TITLE
Evidence of an Overflow field type should be changed

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#15]
Issue:
I spoke with Joe, and he determined the field "Evidence of an Overflow" should be a dropdown menu instead of a toggle.  The options available = Null, Yes, No.

Apply the following business rules:
1.  Default value = Null
2.  If "is the Overflow Active" = No, then Evidence of an Overflow CAN NOT be Null.  Apply this like any other required field (system displays message at a save attempt).

**Comment by kanglu666** [comment]
done
