### ISSUE TITLE
SSO Application - Assign to Email Notification

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#150]
When the "Assigned To" field is changed and the report is saved, the user that the SSO is then assigned to should receive the following email:

**Subject:**  An SSO at [insert location] Has Been Assigned to You!

**Body:**  The SSO report at [insert location] has been assigned to you by [insert full name of last editor] for completion.  Please access the SSO Reporting Mobile Application and check your inbox.  The report should be submitted within 24-hours of the occurrence.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
