### ISSUE TITLE
SSO Application - GPS Pin Graphic Missing

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#151]
**Issue:** When pressing the Zoom to Position button, the app does not display the blue push pin.  It appears that the reference link to that graphic is broken.  This is an issue in both dev and prod.

![image](https://cloud.githubusercontent.com/assets/5805454/4334873/1b86269a-3ff5-11e4-96b7-b32e3128e82e.png)

**Resolution:**  Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
fixed

**Comment by JMurk** [comment]
Confirmed complete on dev and prod
