### ISSUE TITLE
SSO Application - No Buttons When Opening from Inbox

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#152]
**Issue**:  When users with editor permission opens up an SSO from their inbox, the Photos, Save, and Email buttons are missing from the SSO Details.

**Resolution**:  I was not able to re-create the issue with my log in last week, but just had someone come forward with the issue on their iPad.  His name was Gregory Crowder and he was running iOS8.

**Comment by kanglu666** [comment]
if the record "ASSIGNED_TO" value not equal to current login user. 
he will no be able to see all the buttons if he has role editor. otherwise, he should be able to see buttons.

i also cant re-create the issue. tell him do some screen shots, record which SSO he selected.

**Comment by JMurk** [comment]
Logging in as Gregory.Crowder

![image](https://cloud.githubusercontent.com/assets/5805454/4490963/0c8fe84a-4a33-11e4-96be-a324f18ad943.png)

You can see the buttons missing.  His pw is Welcome01 if you need to test.

**Comment by kanglu666** [comment]
fixed on dev, please test

**Comment by JMurk** [comment]
Confirmed complete.  Please push to prod.

**Comment by kanglu666** [comment]
SSO app has been updated at city prod, ready for testing.

**Comment by JMurk** [comment]
Confirmed complete.
