### ISSUE TITLE
SSO Application - Email Report - No Data

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#153]
**Issue**:  The report link that is emailed (24 and 5day) opens a blank report.  This is occurring in production.

**Resolution:** Please investigate and resolve accordingly.

**Comment by JMurk** [comment]
Email links from prod pointing to dev.  Please update.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
