### ISSUE TITLE
SSO Application - New SSO Not Saving - Stuck on Load

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#154]
**Issue:**  In production, I just tried to create a new SSO.  When clicking save, the application gets stuck on the loading screen.

![image](https://cloud.githubusercontent.com/assets/5805454/4461646/23448f32-48bc-11e4-8a00-3900cb81e2dd.png)

**Resolution:**  Please investigate and resolve accordingly.  I suspect there is an issue with the trigger.

**Comment by kanglu666** [comment]
fixed

**Comment by JMurk** [comment]
Confirmed complete.
