### ISSUE TITLE
SSO Application - Delete Record Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#155]
**Issue:**  There is a typo in the delete SSO warning message,

![image](https://cloud.githubusercontent.com/assets/5805454/4528245/3fc35142-4d6d-11e4-9873-6264826194d0.png)

**Resolution:** Please update the message to read "Warning: Are you sure you want to delete this record?"

**Comment by kanglu666** [comment]
updated in dev, please test

**Comment by JMurk** [comment]
Confirmed complete in dev, ready for push to prod.

**Comment by kanglu666** [comment]
updated in PROD

**Comment by JMurk** [comment]
Confirmed complete.
