### ISSUE TITLE
SSO Application - Map Load in Chrome

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#156]
**Issue:**  When loading the application in Google Chrome, the map get stuck on the loading screen until you zoom in or out.  This appears to only be an issue for the SSO application in dev AND PROD.  Prod does not seem to load anything.

![image](https://cloud.githubusercontent.com/assets/5805454/4645399/8c828e24-5468-11e4-94b8-df91cde16b61.png)

**Resolution:**  Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
working fine for me

**Comment by JMurk** [comment]
Seems to be working OK.
