### ISSUE TITLE
SSO Application - DEV - Spatial Autopoulates not Working

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#158]
**Issue:**  The fields that are supposed to auto-populate based on spatial location, are not.

![image](https://cloud.githubusercontent.com/assets/5805454/4703231/08708a28-5869-11e4-8603-8ea5c512492e.png)
![image](https://cloud.githubusercontent.com/assets/5805454/4703243/10c0d0e8-5869-11e4-9bd7-bf2c09c505c1.png)

**Resolution:** Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
Dev sso_boundaries map service is super slow and has some issue. please check that.

**Comment by JMurk** [comment]
Confirmed complete on dev and prod.
