### ISSUE TITLE
SSO Application - Inbox - Admins

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#160]
For all users with the security role of "Admin", please load their inbox with all SSOs with a status of "In Progress"

Admins should also have the ability to edit any SSOs, regardless of who is assigned.

**Comment by kanglu666** [comment]
updated on city DEV, please

**Comment by JMurk** [comment]
Can you also add "Assigned To" to the details of the records in the inbox list?

![image](https://cloud.githubusercontent.com/assets/5805454/4810001/0121120e-5eb0-11e4-893b-e6d83d85b03b.png)

Under Location.

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
