### ISSUE TITLE
SSO Application - New Email

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#162]
Can we fire an email when the Assigned To field is changed?  The email should include the information input by the investigator.

**Comment by kanglu666** [comment]
we have this function in place from the very beginning.
when an sso being updated, and the assign to field not == to the current log in user, an email will be send to the new assigned to user.

**Comment by JMurk** [comment]
Ok... so now the question is can we CC three other people every time this occurs?

**Comment by kanglu666** [comment]
yes, we can. give me the email list

**Comment by JMurk** [comment]
Please email Jerry.Butler@baltimorecity.gov, Kenneth.Smith@baltimorecity.gov, and James.Patrick@baltimorecity.gov whenever the "assigned to" field is changes.  The body of the email should read:

SSO (number) at (location) has been initiated by (initiated by name) and assigned to (new assigned to name.)

To test, you can set up the email to only send to me in the development environment.

**Comment by jday3** [comment]
I need a little clarification.

Currently, the system sends an email to the assignto user when the sso is saved and the the assignto user is not the user that is using the app. Do you want to send an email whenever the sso is saved and the assignto field is changed? (not just when the assignto user is not the current app user). Also the current email that is being sent has the body : "The SSO report has been assigned to you by " + user + " for completion. Please access the SSO Reporting Mobile Application and check your inbox. The report should be submitted within 24-hours of the occurrence. "

Do you want me to change that body or send a separate email?

**Comment by JMurk** [comment]
This will be an entirely new/different email.  Basically, the three emails above are the investigation supervisors.  They requested to be notified when investigators (their staff) hand over work to maintenance supervisors so they can make sure their work is up to par.

If that doesn't make sense, we can discuss tomorrow.

**Comment by jday3** [comment]
That makes sense, thanks.

**Comment by jday3** [comment]
Ready for testing on dev

**Comment by JMurk** [comment]
Looks good.  I have sent an email to the users to see if they are OK with the implementation.

**Comment by JMurk** [comment]
Since I have gotten no response from the users on this issue in a long time, we are going to abandon this enhancement.  It will be reopened if it is requested again.
