### ISSUE TITLE
SSO Application - REMOVE EMAIL FROM 24-Hour

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#165]
Please remove the following emails from the 24-hour report email list:

Lakeisha.Laury@baltimorecity.gov; 
Kumasi.Vines@baltimorecity.gov; 
Eloise.Black@baltimorecity.gov

These people should receive 5-day reports and 5-day report amendments.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
