### ISSUE TITLE
SSO Application - 5-Day Reports - Email to DLs

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#167]
Please update the 5-day and 5-day reports to be emailed to the following:

-5-day reports when "OVER_10000" = 0 (NO) - Send to "DL - 5 day under 10000"
-5-day reports when "OVER_10000" = 1(YES) - Send to "DL - 5 day over 10000"

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed for regular 5-day report.  Will confirm over 10,000 once one occurs.

**Comment by JMurk** [comment]
Closing.
