### ISSUE TITLE
SSO Application - Overflowing Feature Selection - House Connections Selectable

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#169]
This will be a change in workflow.  When selecting the overflowing feature, users may select Clean Outs.  The issue is that the feature class representing Clean Outs are really address points and are thus not always in the location of the actual Clean Out.

To solve this issue, we will remove the points as selectable and make House Connections selectable instead.  When chosen, OVFL_STRUCTURE should be set to CO and the House Connection TAG should we written to the OVERFLOW_TAG field.

**Comment by jday3** [comment]
Done, on dev.

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by JMurk** [comment]
Confirmed complete.
