### ISSUE TITLE
SSO Application - Reports - Evidence Only

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#170]
For ALL reports where OVF_EVIDENCE = 1(Yes), display EST. QUANTITY OF DISCHARGE (GAL: and EST. OVERFLOW (GPM) as "Unknown"

![image](https://cloud.githubusercontent.com/assets/5805454/5457143/9e367d72-8516-11e4-8492-12d302aafca5.png)

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
The reports being emailed from dev are pointing to prod by mistake.  Also when attempting to launch a 24 hour report from the application, a server error is returned:

![image](https://cloud.githubusercontent.com/assets/5805454/5581217/113b5ad2-9024-11e4-8732-dd909805ca09.png)

**Comment by jday3** [comment]
The emails are fixed, and you should be able to see the 24 hour reports on dev now

**Comment by JMurk** [comment]
Confirmed complete on dev.  I noticed that WEATHER CONDITIONS are not displaying in dev (works fine in prod).  Just be sure that bug does not come over when making the push to prod.

![image](https://cloud.githubusercontent.com/assets/5805454/5596487/4b5fe08a-925d-11e4-9726-9eb35ffff265.png)

**Comment by jday3** [comment]
It seems like the app has the wrong domain values set for moderate and heavy rain, so I will need to update it there

**Comment by jday3** [comment]
I went ahead and updated the app on both dev and prod so that it is setting the correct domain values for weather condition. Additionally, I fixed the data that already exists so that the reports for existing SSOs will generate correctly

**Comment by jday3** [comment]
The updated reports are now on prod

**Comment by JMurk** [comment]
Confirmed complete.
