### ISSUE TITLE
SSO Application - Confirmation Message ?

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#171]
**Issue:**  In dev, when emailing the 24-hour report, the system prompts the following contradictory message:

![image](https://cloud.githubusercontent.com/assets/5805454/5569066/ff939922-8f36-11e4-9d54-87e5c2837a2a.png)

I think that the report submission failed since I did not get an email.  However, the message states a success.  

**Resolution:** Please adjust this message so that it clear states a success or failure.  If the reports are not being sent, please address that as well.

**Comment by jday3** [comment]
There was a config error with the web API where it was using an outdated password to send the emails

**Comment by JMurk** [comment]
Please updated the confirmation message text for when a failure occurs.  Just remove "Record Reported Successfully!" sentence from the existing message.

**Comment by jday3** [comment]
Fixed on dev and prod, but I don't think youll be able to test since it is a rare error

**Comment by JMurk** [comment]
I have faith.... Closing.
