### ISSUE TITLE
SSO Application - Initiated By - Populating Incorrectly

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#172]
**Issue:**  The INITIATED_BY and INITIATED_DATE fields are populating on every insert AND update.  It should only populate upon update.

![image](https://cloud.githubusercontent.com/assets/5805454/5569989/c7352738-8f47-11e4-8eb3-9087c7464495.png)

**Resolution:** Please adjust the trigger so that these fields are only edited upon insert.

**Comment by jday3** [comment]
fixed on dev

**Comment by JMurk** [comment]
Confirmed complete.  Please push to prod.

**Comment by JMurk** [comment]
Appears to be working.
