### ISSUE TITLE
SSO Application - Changes in the Features Tab Do Not Save

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#174]
I am getting reports from Steve that changes he makes in the Features form are not making their way into the database.  Specifically the Choked Feature ID.  

This appears to be working in dev OK, just not production.

Please look into this ASAP.

**Comment by jday3** [comment]
This is going to be hard for me to test since I can't create a new SSO. From what I'm seeing in the app code and database in dev, it is working and should be the same in production

**Comment by jday3** [comment]
Is Steve clicking 'Save' everytime?

**Comment by JMurk** [comment]
I just tested in prod and it worked fine.  It must be that he is not saving every time.
