### ISSUE TITLE
SSO Application - 24-Hour Reports - Send to DLs

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#176]
Please point the 24-hour reports to send to the following distribution lists:
- SSO-24hr-over-10000 (when OVR_10000 = 1)
- SSO-24hr-under-10000 (when OVR_10000 = 0)

This change should be made in PROD only.

**Comment by jday3** [comment]
This is done on prod

**Comment by JMurk** [comment]
Steve says he did not receive it

**Comment by JMurk** [comment]
Sorry, the emails are actually
DL-24hrunder10000@baltimorecity.gov
dl-24hrover10000@baltimorecity.gov

**Comment by jday3** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
