### ISSUE TITLE
SSO Application - Change Email Subject Lines for >10000 Gallons

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#177]
Please change the subject line for 24 Hour and 5 Day emails where OVR_10000 = 1 to read:

"OVER 10,000 GALLON SSO Reported at: <location>"

Can you make flag it has high-importance as well?

**Comment by jday3** [comment]
Done on dev. As far as the importance goes, I marked the over 10000 gallon emails as high priority, but that is about all I can do.

**Comment by JMurk** [comment]
That works.  Please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Complete.
