### ISSUE TITLE
SSO Application - Assigned to You Email - Only Send When In Progress

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#178]
**Issue:** Currently the application is designed to fire off an email each time the "Assigned To" field is changed.  I believe this may be sending at times when the SSO is saved without a change to that field, which causes confusion.

**Resolution:**  Please be sure that the email only send when a change is made to that specific field.  ALSO... only fire the email when the status = In Progress.

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Hmm, I don't seem to be getting emails or the notification in the app has been assigned to the selected user.

**Comment by JMurk** [comment]
Confirmed on dev, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Complete.
