### ISSUE TITLE
SSO Application - Preparer and Preparer Title Autopopulate

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#179]
**Issue:**  Preparer and Preparer Title correctly autopopulate when a report is submitted, however it is updated each time a new report is submitted, which is incorrect.  It should only populate when the 24-hour report is submitted (or when those fields are null)

**Resolution:**  Please update so that these field are only populated after 24-hour report submital.

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by JMurk** [comment]
It looks like this this is complete in prod.  Jesse, can you check and confirm please?

**Comment by jday3** [comment]
Yes it is. It came over when I updated the references to the sewer features map service
