### ISSUE TITLE
SSO Application - Report - Photos not Prinitng

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#181]
**Issue:**  The photos sub-report in all reports (24-hour, 5-day, 5-day amended) is failing.

![image](https://cloud.githubusercontent.com/assets/5805454/6047226/6391e1ac-ac76-11e4-9459-5e7694736283.png)

**Resolution:**  Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
fixed, please test

**Comment by JMurk** [comment]
Confirmed complete.
