### ISSUE TITLE
SSO Application - Recently Reviewed List

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#182]
**Issue:**  Currently the "Recently Reviewed" SSO list on the inbox loads all SSOs with a status of 5DAY.  There are too many in the list and it is ordered so that hte most recent are at the bottom.

**Resolution:** Please only load 5DAY SSOs where the Occurrence Date is within the past 60 days.  Also change the display order from newest at the top to oldest at the bottom.

**Comment by jday3** [comment]
Done on dev

**Comment by jday3** [comment]
This was just pushed to prod while updating the date/time offset issue

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by JMurk** [comment]
Please adjust this to be 120 days

**Comment by jday3** [comment]
this was completed and confirmed by steve
