### ISSUE TITLE
SSO Application - Potential late SSO report alert

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/SSO-Application-Issues#184]
Can we set up an email notification if an SSO gets to 4 days without a "5 day report" being filed?

Ideally, an email will be sent out to a DL (being created now in the City) notifying the list that an SSO is nearing the 5 day mark and still needs the 5 day report to be submitted.

Subject:  SSO 5 Day Report Needed

Importance:  High

Text should be:
"An SSO 5 day report is needed for SSO [insert ID].  This SSO 5 day report will be late if not submitted within 24 hours."

**Comment by jday3** [comment]
@BC89, how do you think we should accomplish this? I would think we create a windows service using Quartz to check the database.

**Comment by BC89** [comment]
Doing it with a windows service and quartz should work just fine.

**Comment by jday3** [comment]
@alanfoster99, I just wrote a windows service that runs once a day and sends an email for each SSO that has a status not equal to 5DAY and the SSO_DATE is between 4 and 5 days before todays date. It is running in dev currently and sending the emails to my email address. Let me know an email address you would like me to send to instead for you to test.

**Comment by alanfoster99** [comment]
you can send to my baltimore city account -- alan.foster@baltimorecity.gov

the DL is set up, so we can use that after testing

**Comment by jday3** [comment]
Okay, I just restarted the service so you should have received an email (probably 2 for the same SSO because it runs twice on the initial start up). Note that the service is using the dev database.

**Comment by alanfoster99** [comment]
Worked for me.

The DL is DL-SSOComplianceTeam@baltimorecity.gov

Please go ahead and set it up to use the DL.

Thanks.

**Comment by jday3** [comment]
Is there a certain time of day that you would like it to run? In the morning around 8am?

**Comment by alanfoster99** [comment]
Let's go with midnight

**Comment by jday3** [comment]
I scheduled it to start at midnight tonight

**Comment by alanfoster99** [comment]
Thank you.  Closing.
