### ISSUE TITLE
SSO Application - Choked Features - Add Manholes As Selectable Option

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#185]
Users would like the ability to identify manholes as the choked feature.  Currently the selection is limited to Mainlines and House Connections.

I added it to the domain in Dev and Prod, so it shows up in the features page dropdown.  Just need to add it to the selection functionality.  

![image](https://cloud.githubusercontent.com/assets/5805454/6802583/304068d4-d208-11e4-9c6b-7534e7dc00ca.png)

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Works, but my post above was incorrect.... I was looking at the Overflowing Feature drop down.  We need to add Manhole to the Choke Type drop down.

Sorry about that.

![image](https://cloud.githubusercontent.com/assets/5805454/6826174/e6e02ef8-d2d5-11e4-99c6-7a5ae1336128.png)

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
