### ISSUE TITLE
SSO Application - Auto-Populate Weather Conditions

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#187]
Please add functionality to the SSO application so that weather conditions are automatically populated from an online weather service using the SSO's location (coordinates).

Per Alan, here are some potential sources:

Several free APIs return current conditions based upon lat/long.  Possible sources include forecast.io, NOAA NWS, and Weather Underground.  See:
o   https://developer.forecast.io/
o   http://api-portal.anypoint.mulesoft.com/noaa/api/noaa-national-weather-service-nws-api?ref=apihub
o   http://www.wunderground.com/weather/api

**Comment by jday3** [comment]
Done on dev. I used [Open Weather Map](http://openweathermap.org/weather-conditions) because it has a pretty lax pricing scheme.

**Comment by JMurk** [comment]
Seems a bit off.  Current conditions are clear and 83 degrees.  Please investigate other options

![image](https://cloud.githubusercontent.com/assets/5805454/8239352/41a55878-15c9-11e5-8987-1fb9b7affca1.png)

**Comment by alanfoster99** [comment]
Is this in corrected time or Zulu?

Alan E. Foster
City of Baltimore
Business Analyst and Lead, Data Management Section – Office of Asset Management
1.410.316.0812tel:1.410.316.0812
1.410.396.tel:1.410.396.00220022tel:1.410.396.0022

alan.foster@kci.commailto:alan.foster@kci.com
alan.foster@baltimorecity.govmailto:alan.foster@baltimorecity.gov

[cid:image001.jpg@01D0615E.BF5679C0]http://kci.com/

On Jun 18, 2015, at 14:50, Joe Murk <notifications@github.com<mailto:notifications@github.com>> wrote:

Seems a bit off. Current conditions are clear and 83 degrees. Please investigate other options

[image]https://cloud.githubusercontent.com/assets/5805454/8239352/41a55878-15c9-11e5-8987-1fb9b7affca1.png

**Comment by jday3** [comment]
Corrected time. When I looked deeper at the API I was using, it states that the free use may return data that is up to two hours old. This obviously isn't useful, so I am looking into other APIs

**Comment by alanfoster99** [comment]
Got it -- WUnderground and NOAA looked promising to me -- Dark Sky may only be forecast

**Comment by jday3** [comment]
I just updated it to use [weather.gov](http://forecast.weather.gov/MapClick.php?lat=39.29037897100045&lon=-76.61218662699963&site=all&smap=1#.VYQdV_lVhBc)

**Comment by JMurk** [comment]
Confirmed complete in dev.  Please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
