### ISSUE TITLE
SSO Application - New User Roles

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#188]
There is a need for two new user roles for the SSO Application.  The 'Editor' role will be split into roles called ,Investigator, and ,Supervisor.,  For now both will have the same permissions as the 'Editor' role, except the Email button will be hidden for the Investigator role.

**Comment by jday3** [comment]
Done on dev. I basically just renamed Editor to Supervisor and added Investigator, so you will see that supervisor has a bunch of users and investigator has none.

**Comment by JMurk** [comment]
Looks good.  Please push to prod.

**Comment by jday3** [comment]
Should I just make all users that are currently Editors a Supervisor?

**Comment by alanfoster99** [comment]
Here are the duties by user type:

Investigator sees only these: (Supervisor can see as well)

Occurrence Date
Full Location 
Zip Code (Auto populates)
Weather conditions (Auto populates)
Temperature (Auto populates)
Evidence of an overflow/Was an active overflow observed/Is the overflow still active? (toggle switches)
Observed by
Observed time
Overflow type
Description of discharge
Start date & Time (If active)
Estimated flow (GPM)
Reaching waterway (toggle switch)
Stream/water affected
Watershed (Auto populates)
Sewershed (Auto populates)
311 CSR creation time
Service request type
Service request number

Supervisor only (Investigator cannot see)

Person notified – MDE (If active)
Date/time notified – MDE (If active)
Person notified – HD (If over 10,000 gal. or reaches waterway)
Date/time notified – HD (If over 10,000 gal. or reaches waterway)
Reasons for overflow – Rags, roots, grease, etc. (Toggle switches)
End date and time (if active/abated)
Duration (if active/abated)
Estimated quantity (if active/abated)
Over 10,000? (toggle switch)
Is bypass pumping needed? (toggle switch)
Measure taken
Preventative action taken
Remarks
Work Order type
Work Order number

Supervisor and Investigator:

Both should have access to the pictures and features (overflowing/choked)

***If the supervisor is the first responder he should have access to the entire form and not just the supervisor portion, he acts as the investigator and the supervisor in these cases.

Supervisor gets access to the email button, investigator does not.

**Comment by jday3** [comment]
Okay sounds good. One question though - you mention at the bottom:

`
***If the supervisor is the first responder he should have access to the entire form and not just the supervisor portion, he acts as the investigator and the supervisor in these cases.
`

but earlier you said: 

`
Investigator sees only these: (Supervisor can see as well)
`

I just want to clarify that there aren't any restrictions on what the supervisor sees, regardless of whether they are the first responder.

**Comment by alanfoster99** [comment]
You are correct; I should have worded it as "these are the only fields the investigator sees, while supervisor has access to all"

**Comment by jday3** [comment]
This is ready for testing in dev

**Comment by JMurk** [comment]
As an investigator, I am seeing the Email button still.

**Comment by jday3** [comment]
This should be fixed

**Comment by JMurk** [comment]
Looks good, please push to prod.  Keep all editors in as Supervisors as you did in dev.  We will parse out the investigators from there.

**Comment by jday3** [comment]
Done. I made you an investigator to confirm

**Comment by JMurk** [comment]
Confirmed complete.
