### ISSUE TITLE
SSO Application - Ongoing Overflow

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#189]
Per Steve:  "when an SSO is marked as “ongoing”  the application user is still required to put in an End Date & Time/Duration and Estimated quantity (even though that information is not yet available).  Is it possible to not require the End Date & Time/Duration/Estimated Quantity fields only on SSO reports that are marked as “Ongoing”? ( when the “Is the Overflow Still Active?” toggle switch flipped)."

**Comment by jday3** [comment]
Sure, this can be done. Will implement if you want

**Comment by JMurk** [comment]
Please implement in dev.

**Comment by jday3** [comment]
done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Steve Lampo to confirm in production.

**Comment by JMurk** [comment]
Per Steve Lampo, confirmed complete.
