### ISSUE TITLE
Consistent Issues Locking Up at Saving New SSO

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#19]
Issue:

Upon trying to save a new record, the system locks up at the "Loading..." screen.  The system will spin here for at least 10 minutes.  The browser itself does not lock up, and the animation within the Loading screen is active, however, it does not appear changes are being written to the database.

Steps to reproduce:
1. Tap the New SSO button
2. Tap the screen and follow the prompts to get to the data form
3. Populate required fields and tap Save
4. The system displays the "Loading..." popup and spins indefinitely.

I had this morning for the majority of Thursday, 3/13.  After each "lockup", I closed the SSO browser tab, cleared cache, closed the browser, opened a new browser, and navigated back to the SSO app.

**Comment by leeensminger** [comment]
The record in question does not display in the Inbox - indicating to me that the record is not being saved to the database.

**Comment by leeensminger** [comment]
Discussed with Lu and this appears to occur when a value is entered which violates field types or lengths.  Lu plans to build in functions to force compliance with field types and lengths.

**Comment by kanglu666** [comment]
zipcode field has been changed to a int type field. if user type string in that field and then click save, the system will ask for the zipcode field requied.
