### ISSUE TITLE
SSO Application - Enhanced Security

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#190]
Issue, per Steve:  There have been a couple instances recently where the supervisor was able to send out both the 24-hour and the 5-day report without me being able to QC the final report.  Robert Johnson and Deliah Whitaker were able to send out the 24-hour and 5-day reports for recent SSO events.  Do you have any idea what could be causing this?  The only thing that I can figure is that they are using an older versions of the supplication that (not going through the portal) that still allows them to send out the 5-day report?

Resolution:  As discussed, please add security to the actual function of submitting reports.  Supervisors can submit 24-hour reports, but not 5-day reports.  Investigators can submit neither.

**Comment by jday3** [comment]
done on dev

**Comment by JMurk** [comment]
Please temporarily unhide the Email button for testing purposes.

**Comment by jday3** [comment]
the change has been pushed to production. I will work now on unhiding the email button in dev for testing purposes.

**Comment by jday3** [comment]
okay, i just made it so that the email button never hides. To confirm it is working, you should see a pop up saying 'You do no have permission to do this.' when they shouldn't be able to submit the record. Realistically though, this should never show up since the button is supposed to be hidden.

**Comment by JMurk** [comment]
Confirmed complete.  Please push the enhanced security to production.

**Comment by jday3** [comment]
done
