### ISSUE TITLE
SSO Application - Reports - Label

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#191]
Enhancement:  Please have the reports (both 24 hours and 5 day) label the EST. QUANTITY OF DISCHARGE field as ">100" when the value in that field is under 100.

![image](https://cloud.githubusercontent.com/assets/5805454/10945157/9e71dbd8-82ea-11e5-8082-afb909041486.png)

**Comment by jday3** [comment]
Do you really mean it to be >100 or should it be <100? I made it <100 since I think that makes sense but lmk if it really should be >

**Comment by jday3** [comment]
done on dev, btw

**Comment by JMurk** [comment]
Yes, my fault.  Confirmed complete, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
