### ISSUE TITLE
SSO - Picture Upload Issue

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#193]
Per Steve Lampo:

The mobile SSO application still only allows you to upload one picture at a time. However, the main issue that users mentioned is that after uploading/attaching one picture to an SSO report and then immediately trying to upload another picture the second picture replaces the first one.  In other words it will only allow you to upload one picture (this does not happen all the time but is a reoccurring problem).  A temporary workaround that I found for this problem is uploading your first picture, then backing out to the SSO form, hitting save, and then going back into the photos tab and adding the second picture (this allows you to attach both pictures to the SSO form).

**Comment by taojun545** [comment]
Both the Images Uploader of SSO and Discrepancy were fixed on dev.

Also fixed the bug we discussed on dev:
When deleting the SSO Record, system also need to delete the related images record in database.

**Comment by JMurk** [comment]
Both have been confirmed complete in dev.  Please push the updates to production.

**Comment by taojun545** [comment]
Done on prod.

**Comment by JMurk** [comment]
Confirmed complete.
