### ISSUE TITLE
SSO - Cursor Movement Selection

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#194]
Per Steve Lampo:

Another problem that was brought up in the meeting is the fact that you are unable to move the cursor to a specific point after you type out and extended amount of text for the description/remarks/measures taken etc.  A good example of this is when one of the application users types out a long sentence in the description of discharge field and then wants to make a change somewhere in the middle of the sentence, the user only has the ability to go to the beginning or the end of the sentence and therefore retype the whole description if they want to make a change.  This issue occurs in the other mobile applications as well and is specifically a problem on the ipad/tablet, not on the desktop.

**Comment by taojun545** [comment]
The cursor can be moved into certain part of the sentence by clicking the field. But if the sentence exceeds field length, the cursor can't be moved into excess part.

After researched JS library, it seems be a normal behavior for text field. So I changed following fields into textarea in SSO Details Form:
- Description of Discharge
- Other Description
- Measure Taken
- Preventive Action Taken
- Remarks

The update is on dev.

**Comment by JMurk** [comment]
I agree with that approach.  Confirmed complete on dev, please push to prod

**Comment by taojun545** [comment]
done on prod.

**Comment by JMurk** [comment]
Confirmed complete.
