### ISSUE TITLE
SSO - Evidence Only - Estimated Quantity

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#195]
**Update Description:**  Currently, when a user toggles to _Evidence of an Overflow Only?_ field, the _Estimated Quantity (Gallons)_ field (among others) is disabled.  

 Please change so that _Estimated Quantity (Gallons)_ is no longer disabled.  This should also be a required field (it should be already, but please verify).

![image](https://cloud.githubusercontent.com/assets/5805454/14207107/eb14536a-f7e5-11e5-85d9-7d119c868e7b.png)
![image](https://cloud.githubusercontent.com/assets/5805454/14207105/dfe7b41e-f7e5-11e5-8db3-f30ae1df61bb.png)

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
I am still able to submit the SSO without Est. Quantity populated.

**Comment by taojun545** [comment]
I added logic to validate field "Estimated Quantity (Gallons) " on dev.

**Comment by JMurk** [comment]
Confirmed complete, ready for production

**Comment by taojun545** [comment]
Updated on production.

**Comment by JMurk** [comment]
OK, change of plans.  Can you change it so that Est. Quantity is NOT required?  Please remove the asterisk from the field label as well.

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by taojun545** [comment]
Updated on production.

**Comment by JMurk** [comment]
Confirmed complete.
