### ISSUE TITLE
SSO - Report composition

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/SSO-Application-Issues#196]
Please change the name on the 24hr and 5 day reports from:

"Mr. Dave Lyons"

to

"Ms. Sharon Talley"

**Comment by taojun545** [comment]
I will update both reports.

But do I need to change "5 Day Amended Report" and "Contact Information", which also have that name.

**Comment by alanfoster99** [comment]
Yes please.

Alan E. Foster
City of Baltimore
Lead, Data Management Division – Office of Asset Management
KCI Technologies, Inc. – Geospatial Practice
1.410.316.0812
1.410.396.0022

alan.foster@kci.commailto:alan.foster@kci.com
alan.foster@baltimorecity.govmailto:alan.foster@baltimorecity.gov

[cid:image001.jpg@01D18F57.124C44D0]http://kci.com/

**Comment by taojun545** [comment]
Updated the name in the three reports and Contact Information on dev.

**Comment by alanfoster99** [comment]
Looks good -- please push to production.

**Comment by taojun545** [comment]
Updated the name in the three reports and Contact Information on production.

**Comment by JMurk** [comment]
Confirmed complete in production.
