### ISSUE TITLE
SSO Report - Add SSOID

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/SSO-Application-Issues#197]
Please add the SSOID to the report, to the right of TEMPERATURE and below ZIPCODE; please add for all reports (24hr, 5 day, etc.) :

![image](https://cloud.githubusercontent.com/assets/7118831/15336179/43801c88-1c43-11e6-9fff-395719567d41.png)

**Comment by taojun545** [comment]
Updated on DEV.

**Comment by alanfoster99** [comment]
I was able to view this for an SSO in progress, but not for one in 5 Day status -- please see

http://dpwdev.baltimorecity.gov/SSOReport/SSOReport5DAY.aspx?SSOID=3751

and verify that the header is not populated.

**Comment by taojun545** [comment]
I think the data in DEV database has some issue.

The SSO 3751 shows in GIS_ADMIN.SSO, but not exists in GIS_ADMIN.SSO_HISTORY_LOG, which should be used for generating report. Since there is no data in GIS_ADMIN.SSO_HISTORY_LOG, the report shows empty data.

**Comment by alanfoster99** [comment]
Got it -- thanks.  Verifying with City; will let you know when to deploy.

**Comment by alanfoster99** [comment]
Verified.  Please deploy to production.

**Comment by taojun545** [comment]
Updated on Production.

**Comment by alanfoster99** [comment]
Confirmed.  Closing
