### ISSUE TITLE
Photo Attachment tool rotates photos 90 degrees

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#20]
Issue: 
After attaching photos, the photos are displayed in the thumbnail area as rotated 90 degrees.  Selecting the photo and viewing it larger produces the same result.

Steps to recreate:
1. Create new SSO
2. Tap photos tab to attach photo
3. Select photo and tap Submit
4. View thumbnail display is rotated

Fix:
The system should display the photo as it was imported.

**Comment by kanglu666** [comment]
photo from desktop browser will rotate, photo from ipad will not. 
just ignore this if testing from chrome
