### ISSUE TITLE
Photo attachment tool does not clear file picker attributes after upload

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#21]
Issue:
After picking a photo file and submitting, the image name and description do not clear.  This results in some confusion, especially after adding another photo and the description is still that of the prior photo.

Steps to reproduce:
1. Select a photo to SSO form
2. Tap Submit to submit the photo [the system should clear the file name and description at this time, but does not]

Fix:
After successful submission of a photo, please clear photo attributes.

**Comment by kanglu666** [comment]
According to Sencha Engineering this is a result browser security issue and cannot be fixed. We are not allowed to modify the contents of a input tag with the type of file.
http://www.sencha.com/forum/showthread.php?273410-File-Field-Clear-Icon
