### ISSUE TITLE
Unsaved edits confirmation message

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#26]
Issue:
A confirmation message should be displayed when the user edits a form and then taps elsewhere (outside the form).  The message should alert the user "There are unsaved edits.  Would you like to continue?"  with OK/Cancel options.  If the user taps Cancel the system returns to the form.  If the user taps OK, the edits are NOT saved to the database.

**Comment by kanglu666** [comment]
leave this as future enhancement.

**Comment by JMurk** [comment]
I don't think this is necessary... cancelling and closing.
