### ISSUE TITLE
'Form Not Submitted' Notification Message

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#27]
Issue:
The system should display a notification message when the user (1) saves edits to a new or existing form, (2), does not submit the form, and (3) navigates away from the form.  The notification message should display "The SSO is not submitted", with an OK button.

**Comment by kanglu666** [comment]
submit function will change the record status to submit.
if one record is saved but not submitted, user will always see it in his INBOX. once submit, the record will not show up. but can be view from the map identify function, and it's ready only.
i will keep it as is. but if do need to show user record is not submit, we can do it for future enhancement.

**Comment by leeensminger** [comment]
this is requirement 6.39.  please implement.
