### ISSUE TITLE
SSO ID allows duplicates

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#29]
It is not currently a requirement, but it is possible to generate 2 SSO records with duplicate SSO ID numbers.  

![dupe_sso_id](https://f.cloud.github.com/assets/4103847/2449139/108e907a-aeae-11e3-8a58-5c2f9ce9cb60.JPG)

**Comment by JMurk** [comment]
SSOID should be unique.  It is the primary key for the feature class.  Lets discuss the best way to avoid duplication.

**Comment by kanglu666** [comment]
will be unique
