### ISSUE TITLE
SSO Application - Geocoder Function

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#30]
Issue:  The user would greatly benefit from a geocode function similar to the one in the Utility Viewer.  Currently if a user is not at the location or does not know where it is to manually zoom in, there is no way they can get to the area of interest.

Resolution:  Please add an address search that will allow them to zoom to the input address.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete and functional.
