### ISSUE TITLE
SSO Application - Create New Point - No Scale Tolerance 

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#32]
Issue:  The application should prevent users from creating new SSOs when zoomed out beyond a scale of 1:2000.

Resolution:  Please add a scale tolerance for the Add New SSO function.  When a user tries to add a new SSO beyond 1:2000 a message should be displayed that reads "Cannot Create Point, Please Zoom In to Problem Location First"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
