### ISSUE TITLE
SSO Application - Autopopulate Zipcode

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#33]
Issue:  Add function similar to the sewershed autopopulate for zipcode.  

Resolution:  Add the zipcode feature class to a map service and use it to populate the Zipcode field of intersecting features.

**Comment by JMurk** [comment]
Lu, a new map service called SSO_Boundaries that includes the zipcode feature class and the stormshed feature class that you will need to autopopulate the two fields in the SSO attributes.  Please update.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
