### ISSUE TITLE
SSO Application - Additional Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#35]
Issue:  Add Input for "Was an Active Overflow Observed?" and "Is Bypass Pumping Needed?"

Resolution:
1. Joe to add DB fields
2. Lu to add Application fields.  Active Overflow Observed above Overflow Still Active and Bypass Pumping Below Overflow Still Active.
3. Eric to add to report

**Comment by JMurk** [comment]
Database fields added:  BYPASS_NEEDED and ACTIVE_OBSERVED.  Lu please update application form.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Eric, Please Add the three fields to the report.

**Comment by JMurk** [comment]
Logged in issue #89
