### ISSUE TITLE
SSO Application - Overflow Evidence 

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#36]
Issue:  Inactive Overflow Information is not necessary and "Evidence of an Overflow" label should ready "Evidence of an Overflow Only?"

Resolution:  Remove Inactive Overflow Information as a grouping and change the label of  "Evidence of an Overflow" to "Evidence of an Overflow Only?"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete
