### ISSUE TITLE
SSO Application - Report - Description Values

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#37]
Issue:  Data fields using domains are displaying the coded value in the reports.

Question:  Is there any way to pull the description value from the ArcGIS domain?

Resolution: Investigate a way to use description values instead of coded values.

**Comment by tarheelgis** [comment]
Update to handle domain values. Please check once posted.

**Comment by JMurk** [comment]
Confirmed complete.
