### ISSUE TITLE
SSO Application - Report - Label Not in CAPS

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#38]
Issue:  The Est. Quantity of Discharge field label is in proper case and is not consistent with the rest of the labels on the report.

![image](https://cloud.githubusercontent.com/assets/5805454/2579531/7666fb9a-b9a2-11e3-8df7-f500b73089e4.png)

Resolution:  Please make the label all caps.

**Comment by tarheelgis** [comment]
Fixed Please check once posted.

**Comment by JMurk** [comment]
Confirmed complete
