### ISSUE TITLE
SSO Application - Overflowing Feature List

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#39]
Issue:  Sewer Manholes are at the bottom of the list when selecting the Overflowing feature.

![image](https://cloud.githubusercontent.com/assets/5805454/2579762/430bebf4-b9a5-11e3-9d3a-a733ad448671.png)

Question:  How are the results sorted?

Resolution:  Please sort the results for OVERFLOWING features so that manholes are at the top of the list.  Most times manholes are the feature type that is overflowing and need to be at the top.

**Comment by kanglu666** [comment]
sewer manhole will be the top of the list

**Comment by JMurk** [comment]
Confirmed complete.
