### ISSUE TITLE
Date field menus do not default to current system date

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#4]
Issue:
When selecting a date (anywhere in the application), the system shows the default date value within the scrolling menu as Jan 1, 2013.  The system should display as default the current system date.

Steps to reproduce:
Edit a date value within the SSO form (Occurence Date, Date/Time Notified - MDE, etc.)

Fix:
Display current system date as default date

**Comment by kanglu666** [comment]
fixed
