### ISSUE TITLE
SSO Application - House Connection Zoom Level

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#40]
Issue:  When selecting a House Connection from the list of features, the map zooms to far in.

![image](https://cloud.githubusercontent.com/assets/5805454/2579840/2bb193ae-b9a6-11e3-8626-2bb7b6de1905.png)

Resolution:  Please adjust the zoom scale.  You can use the same scale that is used for manholes.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete
