### ISSUE TITLE
SSO Application - Lateral/CO Points List Display

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#41]
Issue:  Currently, the lateral/co points display the POINT_ID in the list of features.

![image](https://cloud.githubusercontent.com/assets/5805454/2579895/cb48518c-b9a6-11e3-936b-7ffe3636c85a.png)

Resolution:  Please reove the POINT_ID from the list display and replace it with Address.  Should appear as:

2205 Saint Paul St, Lateral/CO Points

**Comment by kanglu666** [comment]
change the display field for the point address layer to the Address

**Comment by JMurk** [comment]
Confirmed complete
