### ISSUE TITLE
SSO Application - Overflow Type Default Value

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#42]
Issue:  The Overflow Type field defaults to a value of "Dry."

![image](https://cloud.githubusercontent.com/assets/5805454/2579970/0520e9cc-b9a8-11e3-95e2-48ae7d45b3d4.png)

Resolution:  Please make this field null or blank by default and force the user to enter a value.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
