### ISSUE TITLE
SSO Application - Selecting Times

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#43]
Issue:  When selecting a time in the app, the clock is 24 hours.

Question: Is there anyway to make it a 12-hour clock with am/pm designations?  This would make it much easier for users.

**Comment by kanglu666** [comment]
keep as 24 hours style, because there will be calculation for seconds.

**Comment by JMurk** [comment]
I'm not sure that I understand.  Lets talk about this.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
confirmed complete.
