### ISSUE TITLE
SSO Application - Load All SSOs

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#44]
Issue: The Load SSOs button on the inbox does not seem to be functioning.

Resolution:  Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
there are over 2000 SSO in the database, right now the load all will just return some records based on the date. we need to talk about this. the app can not return all the sso back to the user.

**Comment by JMurk** [comment]
How many can it load?  We could cahnge it to be "Load the most recent 100 SSOs" or something like that.

**Comment by kanglu666** [comment]
done, change button to "Load All Submitted SSOs - 24 Hours"

**Comment by JMurk** [comment]
Confirmed complete.
