### ISSUE TITLE
SSO Application - Required Field Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#46]
Issue: When a Required Field is missing, the message prompted displays the name of the database field rather the the application field.

![image](https://cloud.githubusercontent.com/assets/5805454/2580741/d936fb04-b9b0-11e3-9bf0-94a32b33d1c6.png)

Resolution:  Please update ALL messages so that they display the application field label rather than the database field name.  If this is not possible, make the message generic.

**Comment by kanglu666** [comment]
field name will be show up.

**Comment by JMurk** [comment]
Confirmed complete
