### ISSUE TITLE
SSO Application - Saving a New Record

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#47]
Issue:  Upon saving a NEW SSO, the system closes the SSO Details and opens the map view.  After the SSO is saved, a message should be prompted notify the user that the record is saved but NOT submitted (see wireframes)

Resolution:  Upon save of a new SSO record, please add a confirmation message and make sure that the app does not navigate away from the SSO details page.

**Comment by kanglu666** [comment]
message box will pop up after the user save an new SSO.
submit SSO can only happen through the inbox.

**Comment by JMurk** [comment]
The message box is correct, however upon save, the SSO details should remain open.  There is no reason restrict the submit to the inbox.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
