### ISSUE TITLE
SSO Application - Add Link to Report

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#48]
Enhancement:  Add a link to the SSO Report within the rows of the inbox.

![image](https://cloud.githubusercontent.com/assets/5805454/2581003/be2aa5d8-b9b3-11e3-8849-5140329328da.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Lu, is there any way to filter the link out on SSO where STATUS = "In Progress" ?

**Comment by kanglu666** [comment]
no, all records in the inbox list will have that view report hyperlink.

**Comment by JMurk** [comment]
Ok. Closing.
