### ISSUE TITLE
SSO Application - Report - Overflowing/Choked Features

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#49]
Issue:  Missing Info on the report for realted features.

Resolution:  Please make the following changes.
-Change to OVERFLOW FEATURE ID.  Field should pull from various data fields determined by the overflow structure.
- Add CHOKE TYPE:
- Change to CHOKED FEATURE ID:

![image](https://cloud.githubusercontent.com/assets/5805454/2581775/649a7580-b9bc-11e3-9f23-770f088b2279.png)

**Comment by tarheelgis** [comment]
Fixed Please check once posted.

**Comment by JMurk** [comment]
Looks good. Closing.
