### ISSUE TITLE
Drop down menu contains blank values

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#5]
Issue:
Upon opening the drop down menu for the Overflow Type field, the first value shown is a blank value.  This value is selectable, but because this field is a required field, it should not allow this value.

Note that this issue is present in at least one other field (Stream Water Affected), but because this field is not required, it needs to have the blank value here.  These drop down menu options should NOT change.

Steps to reproduce:
Within the SSO form, open the drop down menu for Overflow Type.  View the first value.

Fix:
Remove the blank value from the list.

**Comment by kanglu666** [comment]
blank value has been removed, "Wet" is the default value

**Comment by JMurk** [comment]
Can you leave this as NULL by default and force the user to pick one?  If not, the default value should be "Dry"
