### ISSUE TITLE
SSO Application - Stream Water Affected Label

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#50]
Please update the "Stream Water Affected" label to read "Stream/Water Affected"

![image](https://cloud.githubusercontent.com/assets/5805454/2581824/e9135bb0-b9bc-11e3-9878-4a97ee2dcfb3.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
