### ISSUE TITLE
SSO Application - 24-Hour Report Email

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#53]
Issue:  The email body should read:

A SSO has been reported at:  2331 N Fulton Ave
Click Here to View/Download the Report

![image](https://cloud.githubusercontent.com/assets/5805454/2645661/178348fc-bf35-11e3-84b9-4efdcab1ecbf.png)

Please:
1. Remove the SSO ID in (). 
2. Remove the word "Location"
3. Put the address on the first line.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete
