### ISSUE TITLE
SSO Application - Add Sewer Lampholes as an Overflow Feature

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#54]
Please add Sewer Lampholes to the list of selectable Overflowing Features.
1. Joe M to add to Overflow Structure domain list
2. Lu to add to code.

**Comment by JMurk** [comment]
Added as coded value LH.  Also added a field for the ID as OVERFLOWING_LAMPHOLE_ID

Lu,  please add Lampholes to the selectable features for Overflowing features.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
