### ISSUE TITLE
SSO Application - Initial Tap re-do

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#55]
Issue:  The user has no way to re-tap a point in case of a mistake immediately following the first tap.

Resolution:  Not sure what the best method is here, perhaps we should discuss?

**Comment by kanglu666** [comment]
let's talk about this first

**Comment by JMurk** [comment]
Add a button called "Cancel" to this pop up

![image](https://cloud.githubusercontent.com/assets/5805454/2803112/c47844b8-cc96-11e3-9f52-107508522052.png)

**Comment by kanglu666** [comment]
cancel button added

**Comment by JMurk** [comment]
Confirmed complete.
