### ISSUE TITLE
SSO Application - Pick Feature Types from SSO Details Form

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#58]
Issue:  When Overflow or choked features are not selected on the map, the user should be able to select the feature types from the dropdown menu.

Resolution:  When the Overflow and Choked feature IDs are null, make the Feature types editable.  Also, users with QC permissions should be able to edit the feature type and ID.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Need a save button on this page.

**Comment by kanglu666** [comment]
dont need the save button anymore. after making updates for the type and id, the system will automatically pick up the new values when the user save the SSO records.

**Comment by JMurk** [comment]
I see... confirmed complete.
