### ISSUE TITLE
Overflow Start/End date pickers are not stable

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#6]
Issue:
The start and end date value pickers inconsistently show no values in the scroller, and the scroller is not scrollable.  This occured within both the start time and end time fields - however, the issue only affected one field at a time.  Upon tapping "Done" to save the null-value-selection, the system populates that field with the default date of Jan 1 2013 00:00:00 (even though this was not displayed to the user)

Steps to reproduce:
Reproducing this issue may be difficult - 
1. Within the SSO data form, tap the Start Date field and make a selection
2. Tap the End Time field
Also try reversing this order.

Fix:
Please stabilize these fields, if possible.

**Comment by leeensminger** [comment]
I was also, inconsistently, able to generate a date in 2015.  A few minutes later, 2015 was no longer an option within the same SSO form. 

There also appears to be an issue that affects the Duration field (bug #14 ) Please take a broader look at these two date pickers.

**Comment by kanglu666** [comment]
updated, please test, once get error/unstable, please let me know
