### ISSUE TITLE
SSO Application - Update Modal Screen Questions

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#60]
Please change the following modal screen text:

-Change "Can you Identify the Overflowing Feature?" to "Can you Identify the Overflowing Feature on the Map?"

-Change "Can you Identify the Choked Feature?" to "Can you Identify the Choked Feature on the Map?"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Lu-  Can you make the text center aligned?

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
