### ISSUE TITLE
SSO Application - Clearing Graphics

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#64]
Is there anyway to add a "Clear Graphics" button to the application?  Sometimes graphics get stuck on the map view.

**Comment by kanglu666** [comment]
where to add this button? on the top toolbar?

**Comment by JMurk** [comment]
Yeah, I think that would work.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
