### ISSUE TITLE
SSO Application - Preventive Action Required Message Typo

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#65]
Please update this confirmation message to read: "Preventive" instead of "Prevent"

![image](https://cloud.githubusercontent.com/assets/5805454/2742742/d726a5d4-c708-11e3-9297-92e6aa0c6623.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
