### ISSUE TITLE
SSO Application - Add Photos Button

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#66]
Issue:  Please Change the Add Photos button to be just "Photos"

![image](https://cloud.githubusercontent.com/assets/5805454/2742766/221aa0b8-c709-11e3-862c-d10ead722d0e.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Cleared cache and I see no change.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
