### ISSUE TITLE
SSO Application - Not Submitted Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#68]
Please update the following confirmation message to read:  "The 24-Hour report has not been submitted. Continue?"

![image](https://cloud.githubusercontent.com/assets/5805454/2743100/f85b0d9e-c70d-11e3-9ec8-b89054bbfd2e.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
