### ISSUE TITLE
SSO Application - Report - Start & End Date

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#69]
Issue:  Start Date and End Date should also include time.

![image](https://cloud.githubusercontent.com/assets/5805454/2743264/2780a284-c711-11e3-8416-918a7c0f67a5.png)

Resolution:  Add time to the report, also change the labels to "START DATE/TIME" AND END DATE/TIME"

Please assign back to me when complete.

**Comment by tarheelgis** [comment]
These two fields are in the report design and available to be filled.

**Comment by JMurk** [comment]
I still do not see time on the report for these fields.

**Comment by tarheelgis** [comment]
![image](https://cloud.githubusercontent.com/assets/6514808/2963398/9096bcb8-dada-11e3-836b-7789b1b7137a.png)
Here are the fields in the report, they will not show time if there are no times included in the start_datetime. Is there a separate field to hold the times now?

**Comment by JMurk** [comment]
Time should be stored in the same field. Maybe ESRI doesn't like it? I will double check the geodatabase.

**Comment by tarheelgis** [comment]
should be completed now. If the date and time is entered in the feature class it will show in the report.

**Comment by JMurk** [comment]
Confirmed complete.
