### ISSUE TITLE
No method to clear unwanted date values

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#7]
Issue:
The Start Date and End Date fields are not required - but if the user inadvertently selects a date, there is no way to clear the values.

Steps to reproduce:
Within the new SSO data form, enter a start date or end date.  Attempt to clear the values.

Fix:
Please implement a method to clear these fields of their values

**Comment by kanglu666** [comment]
updated, clear button will do this job, please test
