### ISSUE TITLE
SSO Application - Report - Reason For Overflow Other Descriptions

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#70]
Issue:  When Other is selected as an option, the description is not displayed on the report.

![image](https://cloud.githubusercontent.com/assets/5805454/2743349/a7a50832-c712-11e3-9f01-6a94e424ef60.png)

Resolution:  Please add Other Description to the report.  Of possible, only display if OTHER is selected.

**Comment by tarheelgis** [comment]
Update please check when changes post

**Comment by JMurk** [comment]
I still do not see other description. Am I missing something?

**Comment by tarheelgis** [comment]
should be complete

**Comment by JMurk** [comment]
Confirmed complete.
