### ISSUE TITLE
SSO Application - Report - Misspelling 

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#71]
Issue:  Should be "Preventive" not "Preventative" 

![image](https://cloud.githubusercontent.com/assets/5805454/2743384/4cbe0fe4-c713-11e3-8bc6-c545a287d0c2.png)

Resolution:  Please update label.

**Comment by tarheelgis** [comment]
Fixed Please test

**Comment by JMurk** [comment]
Confirmed complete.
