### ISSUE TITLE
SSO Application -Cleanout Point Placement

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#72]
Question:  When a user selects a cleanout as the overflowing feature, can we have the application create the point at the tap location rather then placed on top of the point.  

This is necessary because the features used to spatially represent clean outs are typically not in the correct location.  Most are in the center of the parcel.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
