### ISSUE TITLE
SSO Application - Report - Add Map

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#73]
Please add a Map to the SSO Report output.

**Comment by tarheelgis** [comment]
Added please test

**Comment by JMurk** [comment]
I do not see the map.  Is this is production?  Also, please change the assignee to me when you are finished.

**Comment by tarheelgis** [comment]
You have to click the paging button at the top of the report toolbar. It is on Page2

**Comment by JMurk** [comment]
Oooohhhh duh! Sorry about that- confirmed complete.
