### ISSUE TITLE
Portal - Icons

### ISSUE THREAD

**Issue by jday3** [JMurk/SSO-Application-Issues#74]
We need icons for the portal page for - utility viewer, sso, leak, and fse.

![capture](https://cloud.githubusercontent.com/assets/4439618/2766326/bd1cd500-ca2d-11e3-8d75-09b1c50820e5.PNG)

**Comment by jday3** [comment]
Updated portal view. Suggestions are welcome!
![capture](https://cloud.githubusercontent.com/assets/4439618/2767472/74147fe2-ca38-11e3-999c-a9b398e68b97.PNG)

**Comment by alanfoster99** [comment]
Would it be worthwhile to query the user's device, and have a desktop site and a separate mobile site?

**Comment by JMurk** [comment]
Closing this... will be tracked under the Utility Viewer Repository.
