### ISSUE TITLE
SSO Application - Estimated Volume Required Notification

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#76]
Please change the following dialogue to read:  "Estimated Quantity field is required!"  Also, the label in the application form needs an asterisks to denote it as required.

![image](https://cloud.githubusercontent.com/assets/5805454/2781277/009b1096-cb12-11e3-8284-986151420642.png)

![image](https://cloud.githubusercontent.com/assets/5805454/2781324/80373780-cb12-11e3-8673-6875c2b732a4.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
