### ISSUE TITLE
SSO Application - Saved bu Not Submitted Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#78]
Please update the follwing message to read "The SSO has been saved, but the report has NOT been e-mailed/submitted."

![image](https://cloud.githubusercontent.com/assets/5805454/2789767/8b5f8734-cbb2-11e3-812b-7fe4e3fd98d2.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete
