### ISSUE TITLE
SSO Application - Overflow Type Required Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#79]
Please update the following message to: "Overflow Type is required. Please save first!"

Also, please fix the capitalization anywhere "Please Save First!" is.  Only Please should be capitalized. 

![image](https://cloud.githubusercontent.com/assets/5805454/2800080/59945a44-cc6c-11e3-9e20-5a5f4bc2b742.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
