### ISSUE TITLE
SSO Application - Cleanout ID Displayed

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#80]
When Clean outs are displayed in the Associate Feature list, the point ID is shown.  Can this be updated to show the address instead?

![image](https://cloud.githubusercontent.com/assets/5805454/2803144/2e903aea-cc97-11e3-88b2-25818751bf3e.png)

**Comment by kanglu666** [comment]
if you want to show the address, then need to update the displayed field to the address field in the mxd

**Comment by JMurk** [comment]
Done.  Confirmed complete.
