### ISSUE TITLE
SSO Application - Successfully Submitted Confirmation Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#81]
Please make the following updates to this confirmation message:
1. Change "Successfully" to "Success!"  - Change the text to white
2. Change the Message to read:  "The 24-Hour Report has been sent to the Distribution List."

![image](https://cloud.githubusercontent.com/assets/5805454/2803184/bea0f4bc-cc97-11e3-9b54-6e51c5b699e6.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
