### ISSUE TITLE
SSO Application - Report - Name of Preparer

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#82]
Can you pull the FULLNAME from the SSO_Users table to populate the NAME OF PREPARER field on the report?

![image](https://cloud.githubusercontent.com/assets/5805454/2803371/e66bab56-cc9a-11e3-8769-190d0abbbd21.png)

**Comment by tarheelgis** [comment]
should be completed now

**Comment by JMurk** [comment]
Confirmed complete.
