### ISSUE TITLE
SSO Application - Report - Capitalize Labels

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#84]
Please make the following labels ALL CAPS:

![image](https://cloud.githubusercontent.com/assets/5805454/2803479/496a756a-cc9c-11e3-87a1-81b48c688d86.png)

**Comment by tarheelgis** [comment]
Updated please review when changes post

**Comment by JMurk** [comment]
Labels are not capitalized. Please revisit.

**Comment by tarheelgis** [comment]
Should  be complete

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by JMurk** [comment]
Still an issue on the 5-Day report:

![image](https://cloud.githubusercontent.com/assets/5805454/3515554/ff521224-06d6-11e4-8c93-9778d5f1b7f9.png)

**Comment by JMurk** [comment]
Confirmed complete.
