### ISSUE TITLE
SSO Application - Add Clean Out Location

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#85]
The SSO application should be able to capture the location (F, R, S) of the clean out in a separate field.

Resolution
1. Joe to add field to DB.  Be sure it uses CO_Location domain.
2. Lu to add field in application:  On features screen, under Overflowing feature.  

Question:  Can we hide or grey out this field until Overflowing Feature = Clean Out?

**Comment by tarheelgis** [comment]
Has this been added and does it go on the report?

**Comment by JMurk** [comment]
Just added to the feature class with domain WW_VVT_CO_Location.  It does not need to go on the report.

Lu, please add to the application.

**Comment by kanglu666** [comment]
CO_Location field has been added to the app, and the field will be only available when the overflowing feature type is clean out.

**Comment by JMurk** [comment]
Confirmed complete.
