### ISSUE TITLE
SSO Application - Report - Labels

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#87]
Please add labels to the reports on the right-hand side of the header block:

24-Hour report:  "24-HOUR NOTICE"

5-Day report:  "FINAL REPORT"

**Comment by tarheelgis** [comment]
Once again on this side of the report development we have not discussed any differences between 24 hour and 5 day reporting. We should discuss this further on how it is currently being addressed

**Comment by JMurk** [comment]
There will be two different reports.  Minor but important differences between the two.

**Comment by tarheelgis** [comment]
Should be complete

**Comment by JMurk** [comment]
![image](https://cloud.githubusercontent.com/assets/5805454/3192166/fe1624bc-ece2-11e3-845e-e3bd733b9abb.png)

Header is cut off, please revise.

**Comment by tarheelgis** [comment]
completed please check when code posts

**Comment by JMurk** [comment]
Confirmed complete.
