### ISSUE TITLE
SSO Application - Report - Add Reviewed Info

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#88]
Please add Reviewed By and Review Date to the bottom of the 5-day report ONLY.

![image](https://cloud.githubusercontent.com/assets/5805454/2889648/86108bea-d51f-11e3-9bb9-19a7946fc145.png)

**Comment by tarheelgis** [comment]
These are currently not fields in the DB and I cannot differentiate from the report side whether or not this is being pulled for a single or 5 day report. This may merit further discussions

**Comment by JMurk** [comment]
5-Day report only.  DB updated at KCI.

**Comment by tarheelgis** [comment]
should be complete

**Comment by JMurk** [comment]
Confirmed complete.
