### ISSUE TITLE
SSO Application - Report - Changes to Section 1

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#89]
Please make the following changes in RED to section 1 of the report:

![image](https://cloud.githubusercontent.com/assets/5805454/2889749/38d48f96-d521-11e3-9118-2fb6d800d768.png)

**Comment by tarheelgis** [comment]
What are the appropriate fields for Still active and pumping needed?

**Comment by JMurk** [comment]
ACTIVE = Still active
ACTIVE_OBSERVED = Was an Active overflow observed
BYPASS_NEEDED = Bypass

**Comment by tarheelgis** [comment]
Completed check when changes post

**Comment by JMurk** [comment]
Confirmed complete.
