### ISSUE TITLE
Field label lengths are too long

### ISSUE THREAD

**Issue by leeensminger** [JMurk/SSO-Application-Issues#9]
Issue:
The following field labels are too long:

Section = Other Details
     - Meature Taken to Minimize Di....
                      *_follow up if necessary to fix spelling/typo mistake (no bug logged here)
     - Preventative Action Taken to...
                      *_follow up if necessary to fix spelling/typo mistake (should be Preventive) (no bug logged here)

**Comment by JMurk** [comment]
Lu, please make these updates per my email.  Also, be sure that it says "Preventive"

**Comment by kanglu666** [comment]
fixed

**Comment by leeensminger** [comment]
please update "Meature" ==> "Measure"
please update "Preventative" ==> "Preventive"
