### ISSUE TITLE
SSO Application - Report - Map Section Heading

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#90]
Can the Map Section have a heading similar to SSO Photographs? The "Map of SSO xxx and any associated photos"  is unnecessary and can be removed.

![image](https://cloud.githubusercontent.com/assets/5805454/2919566/784b01ca-d6dc-11e3-967b-b12d8b800bc5.png)

**Comment by tarheelgis** [comment]
Completed review when posted

**Comment by JMurk** [comment]
Confirmed complete.
