### ISSUE TITLE
SSO Application - Stream/Water Affected Capitalization

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#93]
Please make the options in the Stream/Water Affected dropdown in proper case to be consistent with the rest of the application.

![image](https://cloud.githubusercontent.com/assets/5805454/3192022/38974ab4-ece1-11e3-99eb-c29ca66f1660.png)

**Comment by kanglu666** [comment]
the following is what you give me from earlier email. Do you want to make any changes?
Code    Description
ARGO    ARGONNE RUN
ARMI    ARMISTEAD CREEK
BIDD    BIDDISON RUN
CHIN    CHINQUAPIN RUN
COLG    COLGATE CREEK
CRTB    CURTIS BAY
CRTC    CURTIS CREEK
DEAD    DEAD RUN
GUNP    GUNPOWDER FALLS
GWYN    GWYNNS FALLS
HERR    HERRING RUN
HARB    INNER HARBOR
JF  JONES FALLS
LRR LOCH RAVEN RESERVOIR
MAID    MAIDENS CHOICE CREEK
MID MIDDLE BRANCH
MOOR    MOORES RUN
MTPL    MT PLEASANT RUN
NWHB    NORTHWEST HARBOR
PAT PATAPSCO RIVER
SHCV    STONEHOUSE COVE
SR  STONY RUN
TIFF    TIFFANY RUN
WEST    WESTERN RUN

**Comment by JMurk** [comment]
I want the description values to be in proper case.  Example:  DEAD RUN should be Dead Run.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
