### ISSUE TITLE
SSO Application - Evidence Only

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#94]
Please move the "Evidence of an Overflow Only" field under the "Was an Active Overflow Observed?"

![image](https://cloud.githubusercontent.com/assets/5805454/3192078/d77e24ea-ece1-11e3-9a0d-0694f305c8b6.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Can you add a "?" to the end of the label?

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete,
