### ISSUE TITLE
SSO Application - Cancel Button Capitalization

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#95]
Please capitalize "Cancel" for all pop up windows that have Yes/No/Cancel buttons.

![image](https://cloud.githubusercontent.com/assets/5805454/3217871/0786b63e-efe4-11e3-960e-e54755e9ff1e.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
