### ISSUE TITLE
SSO Application - Require Photos

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#98]
Please update the application so that there must be a minimum of two photos associated to the SSO before it is submitted.

When there is not photos, prompt the following message:

"Please add arrival and departure photos before e-mailing the report"

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
I was able to submit a report without any photos attached.

**Comment by JMurk** [comment]
Confirmed complete.
