### ISSUE TITLE
SSO Application - Reorganize SSO Details

### ISSUE THREAD

**Issue by JMurk** [JMurk/SSO-Application-Issues#99]
We need to reorganize the Affected Water section of the SSO details form.  We will actually split it into two sections.  Here is the how the fields should be ordered and how some of the fields should be populated/controlled.

![image](https://cloud.githubusercontent.com/assets/5805454/3291946/bdd55eae-f589-11e3-8067-4e15595780e0.png)

**Comment by kanglu666** [comment]
please let me know once db schema updated. then i will update the layout

**Comment by JMurk** [comment]
Schema Updated:

OBSERVED_BY
OBSERVED_DATETIME

**Comment by kanglu666** [comment]
updated, clear browser cache before testing

**Comment by JMurk** [comment]
Confirmed complete.
